namespace LibSimbolMudah
{
	struct SequenceDescription
	{
		String sequence;
		String result;
		String description;
	};

	runtimeclass SequenceDefinition
	{
		SequenceDefinition();

		void Build(String keysymdef, String composedef);
	}

	runtimeclass SequenceSearcher
	{
		SequenceSearcher(SequenceDefinition definition);

		IVectorView<SequenceDescription> Search(String keyword);
	}

	runtimeclass KeyboardTranslator
	{
		KeyboardTranslator(SequenceDefinition definition);

		void TranslateAndForward(UInt32 vkCode, UInt32 scanCode, Boolean hasCapsLock, Boolean hasShift, Boolean hasAltGr, UInt8 destination);
		void CheckLayoutAndUpdate();
		event Windows.Foundation.TypedEventHandler<KeyboardTranslator, String> OnTranslated;
		event Windows.Foundation.TypedEventHandler<KeyboardTranslator, String> OnInvalid;
	}

	runtimeclass KeyboardHook
	{
		KeyboardHook(KeyboardTranslator translator);

		event Windows.Foundation.TypedEventHandler<KeyboardHook, String> DebugStateChanged;
		event Windows.Foundation.TypedEventHandler<KeyboardHook, String> DebugKeyEvent;
	}
}
