[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.duck]
script_runner = "@shell"
script = '''
cd 3rd-party
git clone --no-checkout https://github.com/derrickstolee/sparse-checkout-example
cd sparse-checkout-example/
git sparse-checkout init --cone
git checkout main
ls
'''

[tasks.my-flow]
dependencies = [
    "format",
    "build",
    "test",
    "duck"
]