namespace simbolmudah_ui
{
    struct SettingsObject
    {
        Boolean HookEnabled;
        Boolean UseHookPopup;
        Boolean NotifyIconEnabled;
        Boolean MainWindowOpened;
    };

    [default_interface]
    runtimeclass AppManager : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        AppManager(Windows.Storage.ApplicationDataContainer localSettings);

        Boolean HookEnabled;
        Boolean UseHookPopup;
        Boolean NotifyIconEnabled;
        Boolean MainWindowOpened;
    }
}