namespace simbolmudah_ui
{
    [default_interface]
    runtimeclass BlankWindow : Microsoft.UI.Xaml.Window
    {
        BlankWindow(
            LibSimbolMudah.KeyboardTranslator translator,
            LibSimbolMudah.KeyboardHook hook,
            LibSimbolMudah.SequenceDefinition definition
        );
    }
}
