import "AppManager.idl";

namespace simbolmudah_ui
{
    [default_interface]
    runtimeclass SettingsPage : Microsoft.UI.Xaml.Controls.Page
    {
        SettingsPage();
        AppManager ViewModel{ get; };
    }
}
