namespace simbolmudah_ui
{
    runtimeclass SequenceDetail
    {
        SequenceDetail(IVectorView<String> sequence, String result, String description, String codepoints);
        SequenceDetail(LibSimbolMudah.SequenceDescription desc);
        IObservableVector<String> Sequence{ get; };
        String Result{ get; };
        String Description{ get; };
        String Codepoints{ get; };
    }
}