namespace in_app_tutorial
{
    [default_interface]
    runtimeclass TutorialDialog
    {
        TutorialDialog();
        Microsoft.UI.Xaml.Controls.ContentDialog GetDialog(
            Microsoft.UI.Xaml.ResourceDictionary resCache, Windows.Foundation.EventHandler<Boolean> hookPopup);
    }
}