name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build
      working-directory: .\libsimbolmudah
      run: cargo build --verbose --features=build-headers,build-annotations,build-x11-defs
    - name: Run tests
      working-directory: .\libsimbolmudah
      run: cargo test --verbose --features=build-headers,build-annotations,build-x11-defs
